Phase03
Star-Academy/Summer1401-SE-Team07 pull request #2
Opened 2022-07-24 22:29 UTC by Taha-Alikhani

Phase 3 C# exercise

Notes:
- The code is not properly commented yet
- StudentDataHandler class visibly does one more than ONE job and has to be broken down into multiple classes

2022-07-25 14:56 UTC, BozorgmehrZia requested changes
فولدر objects بهتره اسمش بشه Models

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/FileManager/FileReader.cs
> +        string fileContent = string.Empty;
چرا یه جا تعریف کردی یه جا مقدار دادی یه جا ریترن کردی؟
همه رو یکی کن

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/FileManager/FileReader.cs
> +        var students = JsonSerializer.Deserialize<List<Student>>(json);
از ؟؟ استفاده کن

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/FileManager/FileReader.cs
> +        var grades = JsonSerializer.Deserialize<List<Grade>>(json);
اینم مث بالایی از ؟؟ استفاده کن

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/Objects/Student.cs
> +            if (this.Lessons.Count > 0)
داخل brace باشه

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/FileManager/FileReader.cs
> +public class FileReader
این خلاف اصل single responsibility ه
الان این کلاس هم داره از فایل میخونه هم داره دیسریالایز میکنه

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/Program.cs
> +        string studentsJson = fileReader.ReadFile(SudentsFilePath);
تمام متغیرای لوکال var باشن

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/Program.cs
> +    private static string SudentsFilePath = "../../Files/JsonData/students.json";
const
اسمشم غلط املایی داره
آدرس فایل هم غلطه

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/Program.cs
> +    private static string GradesFilesPath = "../../Files/JsonData/scores.json";
const
آدرس فایل هم غلطه

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    public List<Student> GetSortedStudents()
تابع اگه استفاده ای نشده ازش پاک شه

2022-07-25 14:56 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    private void addGradeToStudent(Grade grade)
مطابق قاعده اسم توابع توی C# باشه

2022-07-25 14:56 UTC, BozorgmehrZia commented
آقای ادیبی رو هم اضافه کنین به ریویور ها

2022-07-25 16:57 UTC, Taha-Alikhani commented on C# Star Practices/StudentsDataManager/Program.cs
> +    private static string SudentsFilePath = "../../Files/JsonData/students.json";
![image](https://user-images.githubusercontent.com/31014328/180833339-d81eedaa-c30e-496c-a0f2-fb703f380866.png)
آدرس فایل که درسته البته؟

2022-07-25 17:46 UTC, Taha-Alikhani commented
https://www.toptal.com/developers/gitignore/api/csharp

2022-07-26 04:54 UTC, BozorgmehrZia requested changes

2022-07-26 04:54 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/JsonManager/JsonDataSerializer.cs
> +        // use ?? to set default value for nullable type
این کامنته واسه چیه؟

2022-07-26 04:54 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/Program.cs
> +        FileReader fileReader = new FileReader();
همه var باشن

2022-07-26 06:11 UTC, Soltaniant approved these changes

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/JsonManager/JsonDataSerializer.cs
> +        return JsonSerializer.Deserialize<List<Grade>>(json) ?? new List<Grade>();
با توجه به جنریک بودن تابع deserialize میتونیم اینجا به جای دو تا تابع مجزا، از یه تابع استفاده کنیم. با توجه به اینکه موقع کال کردن تابع به جای فرم جنریک چی قرار میدیم خودش میفهمه که باید به چه آبجکتی کستش بکنه.

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/JsonManager/JsonDataSerializer.cs
> +public class JsonDataSerializer
یه نکته کلی تری که وجود داره اینکه فرض کن در آینده داده هامون نه به سکل json  بلکه مثلا در قالب CSV یا XML بهمون داده بشن. در این صورت مجبور به تغییر کد این بخش میشیم. در نتیجه اصل Open/Closed نقض خواهد شد.

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/Program.cs
> +        var scores = jsonDataSerializer.ReadGradesFromJson(gradesJson);
همون مسئله ای که بالاتر اشاره کردم دوباره اینجا صادقه، فرض کن به جای اینکه بخوایم از فایل داده ها رو بخونیم، مثلا از لینک بخونیم. اینجا دوباره یکم چالش بوجود میاد چون ما فقط برنامه رو برای حالت خوندن از فایل نوشتیم و کلی نیست. همون Open/Closed

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    }
شاید بهتر باشه که تابعی برای اضافه کردن دانش آموزا داشته باشیم. کلی تر هستش. طبیعتا برای یک کلاس به اسم StudentDataHandler انتظار این قابلیت وجود داره. در اینجا فقط داریم از طریق کانستراکتور ایجادش میکنیم.

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    }
اینجا فکر کنم بشه این کار رو هم کرد :
return grades.select(g => g.Lesson).Distinct()
این تابع آخری خودش عناصر تکراری یه لیست رو حذف میکنه و لیست جدید رو بر میگردونه

2022-07-26 06:11 UTC, Soltaniant commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    public List<Student> Students { get; private set; }
به طور کلی شاید بد نباشه که به جای لیست از دیکشنری استفاده کنیم برای دانش آموزا. جلوتر یه سری متود سرچ مانند روش کال شده که چون لیسته اردر زمانیش جالب نیست. تقریبا در هر بار اضافه شدن یه نمره به یه دانش آمور باید هزینه این اردر رو بدیم.

2022-07-26 07:32 UTC, RAAvenger reviewed
سلام
خسته نباشی
فکر کنم اشتباها از روی یه برنچ غیر از main این برنچ رو ساختی
حواست باشه اون اونیکی برنچ رو مرج کنی بعد اینیکی رو

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/FileManager/FileReader.cs
> +        }
میتونی از `File.ReadAllText` هم استفاده کنی

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/JsonManager/JsonDataSerializer.cs
> +public class JsonDataSerializer
برای حل این مشکل میتونید از interface استفاده کنید و یه قالب کلی برای  کارتون  در بیارید تا با تغییر تکنولوژی پیاده سازی‌های جدیدی از اون قالب رو داشته باشید.

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Grade.cs
> +public class Grade
میتونی به جای class از [record](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records) استفاده کنی

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Grade.cs
> +        return $"{this.StudentNumber}: {this.Lesson} {this.Score}";
پیشنهاد میکنم تا جایی که مجبور نباشی از this استفاده نکنی

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Lessons.cs
> +public class Lesson
این هم میتونه record باشه

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Lessons.cs
> +    public Lesson GetMarkedLesson(double score){
یه نگاهی به اینترفیس [IClonable](https://docs.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-6.0) بنداز
شاید با اون هم بتونی کارت رو انجام بدی (و اون یکم استانداردتر هست)

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Student.cs
> +public class Student
این هم میتونه record باشه

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Student.cs
> +            if (this.Lessons.Count > 0)
همیشه سعی کن جاهایی که ممکنه با یه شیء null مواجه بشی null Check داشته باشی 

شرط داخل if رو هم میتونی خلاصه کنی به `if (this.Lessons.Any())`
یه تست بکن شاید خود متد Average هم از لیست خالی پشتیبانی بکنه

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Models/Student.cs
> +    public List<Lesson> Lessons { get; set; }
اگر میخوای اینا رو توی کانستراکتور مقدار بدی میتونی بجای `set` از `init` استفاده کنی

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Program.cs
> +        StudentDataHandler studentDataHandler = new StudentDataHandler(students, scores);
`var`

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/Program.cs
> +        // Create student data handler, and get top 3 students
وقتی دیدی کامنت لازمه، متد رو بشکن

2022-07-26 07:32 UTC, RAAvenger commented on C# Star Practices/StudentsDataManager/StudentManager/StudentDataHandler.cs
> +    public List<Student> Students { get; private set; }
اگر قرار نیست چندجا بگی `Students = somthing` از `init` استفاده کن

2022-07-26 12:47 UTC, Taha-Alikhani commented on C# Star Practices/StudentsDataManager/Models/Student.cs
> +            if (this.Lessons.Count > 0)
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.average?redirectedfrom=MSDN&view=netframework-4.8#system-linq-enumerable-average(system-collections-generic-ienumerable((system-single)))
از لیست خالی پشتیبانی نمیکنه البته

2022-07-27 03:52 UTC, BozorgmehrZia requested changes

2022-07-27 03:52 UTC, BozorgmehrZia commented on C# Star Practices/StudentsDataManager/DataManager/Providers/IData.cs
> +    public interface IData
اسمش بهتره IDataReader باشه
یا هرچیزی که اون خوندن دیتا رو نشون بده

2022-07-27 07:10 UTC, BozorgmehrZia approved these changes

2022-07-27 12:23 UTC, RAAvenger approved these changes

2022-07-27 13:14 UTC, merged